services:
  web-flux:
    image: ghcr.io/santiagopraxis/web-flux-one:latest
    context: ./flux-web-final
    dockerfile: Dockerfile
    container_name: flux_web_one_prod
    ports:
      - "4447:3000"
    restart: unless-stopped
    networks:
      - flux-net

networks:
  flux-net:
    external: true
