services:
  web-flux:
    image: ghcr.io/josgarcia1997/web-flux-one:lastest
    context: ./flux-web-final
    dockerfile: Dockerfile
    container_name: flux_web_one
    ports:
      - "3000:3000"
    restart: unless-stopped
